### ISSUE TITLE
Structure handling is broken

### ISSUE THREAD

**Issue by mdorman** [hexmode/xml-rpc-el#3]
I've added a patch in #2; it seems quite clear to me that it's been broken for a while, and it would be nice if an un-broken version could make it into the elisp package pipeline.

**Comment by mdorman** [comment]
This has been resolved for a while; it would be nice if this could be tagged so it'll be picked up by melpa-stable (and perhaps pushed to marmalade)

**Comment by hexmode** [comment]
I don't know what I need to tag it with, but I'll merge the patch.

**Comment by mdorman** [comment]
Simply adding a tag like 1.6.11 would take the current state of HEAD as version 1.6.11 (which is what matches the value inside of xml-rpc.el itself).  That said, it might make more sense to actually change that version number to 1.6.12 (or whatever) and then tag *that* with the appropriate version number.

melpa-stable will then take care of the rest automatically.

**Comment by mdorman** [comment]
So, it seems to me that this issue could be closed, and could I reiterate the request for a tag for 1.6.11, or perhaps tweaking the release # to be 1.6.12 and tagging that?

**Comment by hexmode** [comment]
My commit in 0ab093d was meant to fix this.  Oh well.... I've not quite got the hang of github.

Note that trying to byte-compile gives me:
```
Compiling file .../xml-rpc-el/xml-rpc.el at Sat Apr 30 18:02:43 2016
xml-rpc.el:257:27:Error: Lisp nesting exceeds `max-lisp-eval-depth'

**Comment by mdorman** [comment]
The change still isn't tagged, which means it still won't show up in melpa-stable.  All you need to do is:

```
git tag 1.8.12  0ab093d
git push --tags
```

**Comment by hexmode** [comment]
tagged

**Comment by mdorman** [comment]
Awesome!  Thanks!
